### ISSUE TITLE
P5.3 integration: "'java.awt.geom.Ellipse2D$Float' object is not callable" in `createGraphics.ellipse()`

### ISSUE THREAD

**Issue by tildebyte** [jdf/processing.py#166]
Specifically in **Basics/Structure/CreateGraphics**. Works in Java mode.

````java
TypeError: 'java.awt.geom.Ellipse2D$Float' object is not callable
````

Minimal(?) example
````python
def setup():
    size(640, 360)
    global pg
    pg = createGraphics(400, 200)


def draw():
    pg.beginDraw()
    pg.ellipse(30, 30, 60, 60)
    pg.endDraw()

    image(pg, 120, 60)
````

**Comment by jdf** [comment]
Can't repro. It's very likely that I fixed this when I fixed #164.

**Comment by tildebyte** [comment]
I'm not sure what I'm doing wrong, but I built mode version 3004 (it's not showing up as an update in the PDE...) and I'm still seeing this.
OSX 10.10.5.
Processing 3.0.1 downloaded from the website.
P5.py built against P5 source only through 3.0.1 commit.
Built with JDK 1.8.0_51.

**Comment by jdf** [comment]
Still can't repro.

![screen shot 2015-11-22 at 11 18 41 pm](https://cloud.githubusercontent.com/assets/55948/11329835/781c7e0a-916f-11e5-8566-330670341c99.png)

**Comment by jdf** [comment]
Are pixelDensity() and displayDensity() present for you? If not, then you're certainly running an old version.

**Comment by tildebyte** [comment]
Sorry, should have thought of that. I'll check.
